---
title: "CodeBook"
author: "Dimitrios Tourountsis"
date: "26/07/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This code book describes the data, variables and transformations performed to clean up the data.

## Data
Data were downloaded and extracted from 
[Human Activity recognition dataset](http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones)

## Transformations
#### Assigned downloaded files to following variables:
* features (features.txt)
* activities (activity_labels.txt)
* subject_test (/subject_test.txt)
* x_test (test/X_test.txt)
* y_test (test/y_test.txt)
* subject_train (test/subject_train.txt)
* x_train (test/X_train.txt)
* y_train (test/y_train.txt)

### Merged the training and the test sets and created one data set
* X created by merging x_train and x_test using rbind() function
* Y created by merging y_train and y_test using rbind() function
* Subject created by merging subject_train and subject_test using rbind() function
* Merged_Data created by merging Subject, Y and X using cbind() function

### Extracted only the measurements on the mean and standard deviation for each measurement
* TidyData created by subsetting Merged_Data
* Selected only columns: subject, code and the measurements on the mean and standard deviation (std) for each measurement

### Used descriptive activity names to name the activities in the data set
* Replaced numbers in code column of the TidyData with corresponding activity taken from second column of the activities variable
* Labeled the data set with descriptive variable names:
  + code column in TidyData renamed into activities
  + All Acc in column’s name replaced by Accelerometer
  + All Gyro in column’s name replaced by Gyroscope
  + All BodyBody in column’s name replaced by Body
  + All Mag in column’s name replaced by Magnitude
  + All start with character f in column’s name replaced by Frequency
  + All start with character t in column’s name replaced by Time

### Created a second, independent tidy data set with the average of each variable for each activity and each subject
* SecondTidyData created using group_by() and Summarise_all() functions
* SecondTidyData exported into SecondTidyData .txt file.
